version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
  pgjson:
    build: ./pg
    depends_on:
      - postgres
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
  mysqljson:
    build: ./mysql
    depends_on:
      - mysql
  mariajson:
    build: ./mariadb
    depends_on:
      - mysql